spring:
  datasource:
    url: jdbc:postgresql://postgresql-server:5432/KtJournalPrompts
    username: ktjpusr
    password: ktjpheaven
    # driverClassName: org.postgresql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    # validate: validate the schema, makes no changes to the database.
    # update: update the schema.
    # create: creates the schema, destroying previous data.
    # create-drop: drop the schema at the end of the session.
    # ddl-auto: create-drop
  sql:
    init:
      platform: PostgreSQL
