journalpromptserver:
  version: '@project.version@'
  name: '@project.name@'
  artifact:
    name: '@project.artifactId@'
    group: '@project.groupId@'

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging.level:
  uk.co.droidinactu: TRACE
  org.spring: INFO
  org.springframework: INFO
  org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
